name: TARS
options:
  bundleIdPrefix: com.orsen
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: TARS
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    ENABLE_PREVIEWS: YES

targets:
  TARS:
    type: application
    platform: iOS
    sources:
      - path: TARS
    info:
      path: TARS/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.orsen.tars
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: TARS/Resources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
